### ISSUE TITLE
End to End working of Beckn gemini P2P usecase using langraph

### ISSUE THREAD

**Issue by emmayank** [beckn/transactional-ai-bap#126]

**Comment by ankitShogun** [comment]
11th Nov Updated - 

1. Started working on the consumer flow
2. Was having some issues again with image upload. Had to send the images the twillio way.
3. Twillio uploads the image or doc to a cloud storage and then share the URL. Uploaded on google drive and shared the link using postman for testing.

**Comment by ankitShogun** [comment]
12th Nov Update - 

1. Image upload was working fine but LLM (Gemini currently) was giving some issues
2. In some scenarios, it returned incomplete messages (Like confirmation for some instructions already provided). Missed couple of things during refactoring. Fixed that
3. Also had to re-write some langgraph initiation code. Was using some custom made things. Replaced it with langgraph native library methods for adding a node and edge.
4. Added support for [langsmith](https://www.langchain.com/langsmith) which lets me see the operation of graph using a GUI on every graph run

**Comment by ankitShogun** [comment]
13th Nov Update - 

1. Nodes and edges were working fine but graph operation was not stopping even though we needed user response and confirmation
2. Like asking the user for uploading signing up and all.
3. Added support for [human-in-the-loop](https://langchain-ai.github.io/langgraph/concepts/human_in_the_loop/) to do that
4. Added breakpoints between nodes to support point no. 3. Breakpoints simply means to stop the execution of graph at a certain point after evaluating that we need a human response

**Comment by ankitShogun** [comment]
14th Nov update - 

1. Added the support of threads for session management. WhatsApp number was being used as thread id. Thread basically is a session and it is continued based on the last interaction
2. Wrote remaining nodes and edges

**Comment by ankitShogun** [comment]
[This](https://github.com/beckn/transactional-ai-bap/tree/feature/langgraph-updated) is the current updated branch. Will only merge it with main after thorough testing
