### ISSUE TITLE
Setup EC2 Instance for Google for India Demo

### ISSUE THREAD

**Issue by emmayank** [beckn/transactional-ai-bap#96]
## Description
Set up a T2.xlarge EC2 instance for the Google for India demo with subdomain mappings, SSL, reverse proxy configuration, and proxy pass to specified ports. Install Strapi and configure ONIX deployment as well.

## Goals
- [x] Set up one T2.xlarge EC2 machine.
- [x] Map the following subdomains to the EC2 instance and configure SSL with reverse proxy and proxy pass to their respective ports:
  - bap-ps-client-ueip2p.becknprotocol.io 
  - bap-ps-network-ueip2p.becknprotocol.io 
  - bpp-ps-client-ueip2p.becknprotocol.io 
  - bpp-ps-network-ueip2p.becknprotocol.io 
  - registry-ueip2p.becknprotocol.io 
  - gateway-ueip2p.becknprotocol.io 
  - bpp-unified-strapi-ueip2p.becknprotocol.io 
- [x] Install Strapi and configure it as required.
- [x] Set up ONIX deployment on the EC2 instance.

## Expected Outcome
- A fully operational T2.xlarge EC2 instance configured for the Google for India demo.
- Subdomains are mapped with SSL, reverse proxy setup, and proxy pass to their respective ports.
- Strapi and ONIX are installed and configured on the instance.

## Acceptance Criteria
- [x] T2.xlarge EC2 machine is set up.
- [x] Subdomains are mapped and accessible with SSL and reverse proxy configuration to the specified ports.
- [x] Strapi is installed and functioning.
- [x] ONIX deployment is configured and operational.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
- AWS EC2
- Subdomain mapping and SSL configuration
- Reverse proxy configuration (Nginx or Apache)
- Strapi installation and configuration
- ONIX deployment

## Complexity
Medium

## Category
Infrastructure Setup

## Sub Category
EC2 Instance Setup

**Comment by em-tpt-bbandi** [comment]
created t2.xlarge instance for the demo 

![Image](https://github.com/user-attachments/assets/73a6e29a-05f2-46ce-8c8e-f98f5ca50be0)

Mapped the following subdomains to the EC2 instance and configure SSL with reverse proxy and proxy pass to their respective ports:
bap-ps-client-ueip2p.becknprotocol.io
bap-ps-network-ueip2p.becknprotocol.io
bpp-ps-client-ueip2p.becknprotocol.io
bpp-ps-network-ueip2p.becknprotocol.io
registry-ueip2p.becknprotocol.io
gateway-ueip2p.becknprotocol.io
bpp-unified-strapi-ueip2p.becknprotocol.io
gcl-ueip2p.becknprotocol.io


![Image](https://github.com/user-attachments/assets/8fb5194c-c3cb-48cb-8a8a-1359c314a8cc)

**Comment by emmayank** [comment]
Review Completed
