### ISSUE TITLE
Deploy beckn-gemini-bap code and setup ci/cd

### ISSUE THREAD

**Issue by emmayank** [beckn/transactional-ai-bap#97]
## Description
Deploy the `beckn-gemini-bap` codebase and set up a CI/CD pipeline for automated deployment and testing. The CI/CD setup will ensure smooth, continuous integration and delivery of updates. The process should involve configuring the pipeline to automatically deploy code changes to the relevant environments and handle tests.

## Goals
- [x] Deploy the `beckn-gemini-bap` code to the required environment.
- [x] Set up a CI/CD pipeline to automate the deployment process.
- [x] Integrate the pipeline with a version control system (e.g., GitHub) to trigger builds upon code pushes.
- [x] Implement automated testing as part of the CI/CD process.
- [x] Ensure that the deployment pipeline can handle both staging and production environments.

## Expected Outcome
- A fully deployed `beckn-gemini-bap` application.
- CI/CD pipeline that automates code deployment, testing, and delivery for both staging and production environments.
- Reduced manual intervention in the deployment process and faster delivery of code changes.

## Acceptance Criteria
- [x] The `beckn-gemini-bap` code is deployed and operational in the appropriate environment.
- [x] The CI/CD pipeline is configured to trigger automatic deployments based on Git commits.
- [x] Automated tests are integrated into the pipeline and executed during the build process.
- [x] Successful deployments are achieved for both staging and production environments.
- [x] The pipeline is tested and confirmed to work with minimal manual intervention.

## Mockups / Wireframes
NA

## Product Name
Beckn Gemini

## Domain
Energy

## Tech Skills Needed
- AWS Amplify
- AWS SNS (Simple Notification Service) or AWS CloudWatch
- Slack API or integration tools
- Notification setup and testing

## Complexity
Low

## Category
CI/CD Setup

## Sub Category
Deployment Automation

**Comment by prasad-takale-eminds** [comment]
We have created the CICD pipeline to deploy the beckn-gemini-bap on the EC2 instance. 
Below is the Jenkins job URL. 
https://jenkins.becknprotocol.io/job/gemini/

SS job executed. 
![Image](https://github.com/user-attachments/assets/2386970c-1bba-4846-b888-1332992285e7)

**Comment by emmayank** [comment]
Review Completed
